name: Go Build and Test on Tag

on:
  push:
    tags:
      - '*'  # Déclenche l'action sur tout tag créé

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Modifier selon la version de Go souhaitée

      - name: Run Tests
        run: go test ./...

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test  # Assure que les tests réussissent avant de construire

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Application
        run: go build -o myapp ./

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-binary
          path: myapp

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-binary

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: myapp
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


